# Generated by Django 5.0 on 2023-12-18 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_remove_book_publication_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='description',
        ),
    ]
