# Generated by Django 5.0 on 2023-12-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField(null=True)),
                ('expiried_date', models.DateField(null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
